In [1]:
import numpy as np

In [23]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [21]:
arr[0]=90
print(arr)
temp=arr[0]
arr[0]=arr[2]
arr[2]=temp
print(arr)

[90  2  3  4  5]
[ 3  2 90  4  5]


In [24]:
# reversing an array in python
#l=arr.len
# print(l)
length=np.shape(arr)
l=length[0]
print(l)
print(type(0))
i,j=0,l//2
for index in range(i,j):
    temp=arr[index]
    arr[index]=arr[l-index-1]
    arr[l-index-1]=temp
    
# reversed array is
print("reversed array is")
print(arr)

5
<class 'int'>
reversed array is
[5 4 3 2 1]


5
<class 'int'>


In [7]:
# multiply t ocoloumn cectors
# cant' multiply lists but can doe element wise opeartyion with arrays of same shape
import numpy as np
v1=np.array([1,2,3,4])
v2=np.array([3,3,3,4])
print(type(v1))
print(v1*v2)# v1*v2 is like broadcasting

<class 'numpy.ndarray'>
[ 3  6  9 16]


In [8]:
x=np.arange(10)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [5]:
l=list([1,2,43,4])
print(l)
l[2]=22
print(l)


[1, 2, 43, 4]
[1, 2, 22, 4]


#### NOTE-> np.sum(np_array) gives sum of all elements and sum(np_array) a matrix whose column are having sum of previous
#### matrix's columns

In [10]:
import numpy as np
ar=np.array([[1,2],[3,4]])
sm=np.sum(ar)
print(sm)
sm2=sum(ar)
print(sm2)


10
[4 6]


In [11]:
mn=ar.mean()
print(type(mn),mn)

<class 'numpy.float64'> 2.5


In [12]:
mn_2=np.mean(ar)
print(mn_2)

2.5


In [13]:
matrix_sq=ar**2
print(matrix_sq)

[[ 1  4]
 [ 9 16]]


In [15]:
import numpy as np
X=np.array([[1,2,3],[4,5,6]]) #matrix->(2,3)
Y=np.array([1,1,1])# vector -> (3,)
Y_mat=Y.reshape((-1,1))
print(X.shape,Y.shape)
result_1=np.dot(X,Y.T)
print(result_1.shape)
print(result_1)
# access elements of result_1 
print("elements are",result_1[0],type(result_1[0]))
print(Y_mat.shape)
print(type(Y))
print(type(Y_mat))
Y_mat
# NOTE-=> np.dot Documention

(2, 3) (3,)
(2,)
[ 6 15]
elements are 6 <class 'numpy.int32'>
(3, 1)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([[1],
       [1],
       [1]])

In [22]:
mt=np.dot(X,Y.T)
print(type(np.dot(X,Y.T)))
print(mt.shape)# is also a vector
print(Y.T)
print(Y.T.shape)
print(type(Y.T))


<class 'numpy.ndarray'>
(2,)
[1 1 1]
(3,)
<class 'numpy.ndarray'>


In [23]:
print(np.dot(X,Y))# x-> (2,3) and Y-> a vector(like (1,3))
# so can multiply X

[ 6 15]


In [24]:
print(np.dot(X,Y.T))# all are same
print(np.dot(X,Y.T))
print(np.dot(X,Y))

[ 6 15]
[ 6 15]
[ 6 15]


In [29]:
print(Y)
print(Y.shape,Y.T.shape)
# vector and it;s transpose's shape remain same

[1 1 1]
(3,) (3,)


In [27]:
# NOTE-> np.dot(matrix,vector) then vector ill change it;s shape according to the rule of matrox
# multiplication
Y__=np.array([1,2])# vector-> (2,)
print(Y__.shape,X.shape)
#print(np.dot(X,Y__))
print(np.dot(X,Y__.T))

(2,) (2, 3)


ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [31]:
# (2,3) and (2,) -> not valid in np.dot(a,b)
# But (2,) and (2,3) are
# and also X.T (3,2) and (2,) are also valid
print(np.dot(Y__,X))# return a vector not a matrix of (3,1)
print(np.dot(X.T,Y__))

[ 9 12 15]
[ 9 12 15]


In [35]:
# np.dot(a,b)-> if both are 1-D matrix not vector then it'll return
XX=np.array([[1,2,3],[4,5,6]])
print(XX.shape)
YY=np.array([[4],[4],[4]])
print(YY.shape)
# matrix multiplication

mx=np.dot(XX,YY) # not a vector it's a matrix of (2,1)
print(mx.shape)
print(mx)

(2, 3)
(3, 1)
(2, 1)
[[24]
 [60]]
