In [1]:
import numpy as np
X=np.array([[1,2,3],[4,5,6]]) #matrix->(2,3)
Y=np.array([1,1,1])# vector -> (3,)
Y_mat=Y.reshape((-1,1))
print(X.shape,Y.shape)
result_1=np.dot(X,Y.T)
print(result_1.shape)
print(result_1)
# access elements of result_1 
print("elements are",result_1[0],type(result_1[0]))
print(Y_mat.shape)
print(type(Y))
print(type(Y_mat))
Y_mat
# NOTE-=> np.dot Documention

(2, 3) (3,)
(2,)
[ 6 15]
elements are 6 <class 'numpy.int32'>
(3, 1)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([[1],
       [1],
       [1]])

In [2]:
mt=np.dot(X,Y.T)
print(type(np.dot(X,Y.T)))
print(mt.shape)# is also a vector
print(Y.T)
print(Y.T.shape)
print(type(Y.T))


<class 'numpy.ndarray'>
(2,)
[1 1 1]
(3,)
<class 'numpy.ndarray'>


In [3]:
print(np.dot(X,Y))# x-> (2,3) and Y-> a vector(like (1,3))
# so can multiply X

[ 6 15]


In [4]:
print(np.dot(X,Y.T))# all are same
print(np.dot(X,Y.T))
print(np.dot(X,Y))

[ 6 15]
[ 6 15]
[ 6 15]


In [5]:
# NOTE-> np.dot(matrix,vector) then vector ill change it;s shape according to the rule of matrox
# multiplication

In [6]:
print(Y)
print(Y.shape,Y.T.shape)
# vector and it;s transpose's shape remain same

[1 1 1]
(3,) (3,)


In [7]:
# NOTE-> np.dot(matrix,vector) then vector ill change it;s shape according to the rule of matrox
# multiplication
Y__=np.array([1,2])# vector-> (2,)
print(Y__.shape,X.shape)
#print(np.dot(X,Y__))
print(np.dot(X,Y__.T))

(2,) (2, 3)


ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [8]:
# (2,3) and (2,) -> not valid in np.dot(a,b)
# But (2,) and (2,3) are
# and also X.T (3,2) and (2,) are also valid
print(np.dot(Y__,X))# return a vector not a matrix of (3,1)
print(np.dot(X.T,Y__))

[ 9 12 15]
[ 9 12 15]


In [9]:
# np.dot(a,b)-> if both are 1-D matrix not vector then it'll return
XX=np.array([[1,2,3],[4,5,6]])
print(XX.shape)
YY=np.array([[4],[4],[4]])
print(YY.shape)
# matrix multiplication

mx=np.dot(XX,YY) # not a vector it's a matrix of (2,1)
print(mx.shape)
print(mx)

(2, 3)
(3, 1)
(2, 1)
[[24]
 [60]]


In [ ]:
# add something