In [1]:
import numpy as np
X=np.array([[1,2,3],[4,5,6]]) #matrix->(2,3)
Y=np.array([1,1,1])# vector -> (3,)
Y_mat=Y.reshape((-1,1))
print(X.shape,Y.shape)
result_1=np.dot(X,Y.T)
print(result_1.shape)
print(result_1)
# access elements of result_1 
print("elements are",result_1[0],type(result_1[0]))
print(Y_mat.shape)
print(type(Y))
print(type(Y_mat))
Y_mat
# NOTE-=> np.dot Documention

(2, 3) (3,)
(2,)
[ 6 15]
elements are 6 <class 'numpy.int32'>
(3, 1)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([[1],
       [1],
       [1]])

In [2]:
mt=np.dot(X,Y.T)
print(type(np.dot(X,Y.T)))
print(mt.shape)# is also a vector
print(Y.T)
print(Y.T.shape)
print(type(Y.T))


<class 'numpy.ndarray'>
(2,)
[1 1 1]
(3,)
<class 'numpy.ndarray'>


In [3]:
print(np.dot(X,Y))# x-> (2,3) and Y-> a vector(like (1,3))
# so can multiply X

[ 6 15]


In [4]:
print(np.dot(X,Y.T))# all are same
print(np.dot(X,Y.T))
print(np.dot(X,Y))

[ 6 15]
[ 6 15]
[ 6 15]


In [5]:
# NOTE-> np.dot(matrix,vector) then vector ill change it;s shape according to the rule of matrox
# multiplication

In [6]:
print(Y)
print(Y.shape,Y.T.shape)
# vector and it;s transpose's shape remain same

[1 1 1]
(3,) (3,)


In [7]:
# NOTE-> np.dot(matrix,vector) then vector ill change it;s shape according to the rule of matrox
# multiplication
Y__=np.array([1,2])# vector-> (2,)
print(Y__.shape,X.shape)
#print(np.dot(X,Y__))
print(np.dot(X,Y__.T))

(2,) (2, 3)


ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [8]:
# (2,3) and (2,) -> not valid in np.dot(a,b)
# But (2,) and (2,3) are # as vector can be (1,2)-row or (2,1)-column
# and also X.T (3,2) and (2,) are also valid
print(np.dot(Y__,X))# return a vector not a matrix of (3,1)
print(np.dot(X.T,Y__))

[ 9 12 15]
[ 9 12 15]


In [9]:
# np.dot(a,b)-> if both are 1-D matrix not vector then it'll return
XX=np.array([[1,2,3],[4,5,6]])
print(XX.shape)
YY=np.array([[4],[4],[4]])
print(YY.shape)
# matrix multiplication

mx=np.dot(XX,YY) # not a vector it's a matrix of (2,1)
print(mx.shape)
print(mx)

(2, 3)
(3, 1)
(2, 1)
[[24]
 [60]]


In [3]:
import numpy as np

#convert a (n,) vector to matrix (n,1)
vec=np.array([1,2,3,4])
print(vec.shape)
mat_vect=vec.reshape((-1,1))
print(mat_vect.shape)

(4,)
(4, 1)


In [6]:
# if both a,b are vectors
v1=np.array([1,2,3,4])
v2=np.array([2,2,2,2])
print(v1.shape,v2.shape)
res_v=np.dot(v1,v1)# matrix multiplication
res_m=v1*v2# broadcasting
print(res_v)
print(res_m)
print(res_v.shape)# an integer/number
print(res_m.shape)
# type
print(type(res_v))
print(type(res_m))

(4,) (4,)
30
[2 4 6 8]
()
(4,)
<class 'numpy.int32'>
<class 'numpy.ndarray'>


In [7]:
# NOT#_> matrix multiplication of (1,3)->m and (3,)-> vector 
# and also matrix multiplication of (1,3)->m and (3,1)->m
m1=np.array([[1,2,3]])
m2=np.array([[1],[2],[3]])
v1=np.array([3,3,3])
print(m1.shape)
print(m2.shape)
print(v1.shape)
r1=np.dot(m1,v1)# a vector -> means we are not getting scalar,we'll get scalar only if we are matrix multiplication of two vectors of same no of elements or same shape
r2=np.dot(m1,m2)# a matrix of (1,1)
print("shapes of results are")
print(r1.shape)
print(r2.shape)
print(r1)
print(r2)

(1, 3)
(3, 1)
(3,)
shapes of results are
(1,)
(1, 1)
[18]
[[14]]
