In [4]:
import numpy as np
a=np.arange(10) +5 # indexing starts from 5
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
print(a)
print(type(a))

[ 5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [16]:
#Use of np.random module
#1 shuffle
import numpy as np
a=np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 9 3 0 7 2 6 5 4 8]


In [17]:
a_1=np.random.rand(2,3)
print(a_1)
a_2=np.random.randn(2,3)
print(a_2)

[[0.07373954 0.61419956 0.30395091]
 [0.60201575 0.22331125 0.8160053 ]]
[[ 0.2389481   0.69005814 -1.13870478]
 [-0.78762076  0.85003786 -0.10003689]]


In [20]:
# returns random integers(in  from of array => random integer array) from given range ando no of integers we want 
a_3=np.random.randint(2,6,4)
print(a_3)
print(type(a_3))

[3 2 5 3]
<class 'numpy.ndarray'>


In [27]:
# pick one random element form given DS(only list and tuple::: can't use foe set and dict)
element_1=np.random.choice([1,2,3,4,54,5])
 #elememt_2=np.random.choice({1,2,3,4,4})
#element_3=np.random.choice({"name":"amit","last_name":"jakhar","roll_no":182106})
print(element_1)
element_4=np.random.choice((1,2,3,4))
#print(element_2)
print(element_4)
#element_5=np.random.choice(1,2,3,4,43)
#print(element_5)

54
1
