In [1]:
import numpy as np

In [5]:
#create an array using Numpy Library
a=np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape) # size of matrix,shape is attribute not method
print(a[1])

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
2


In [6]:
# shape returns a tuple
print(type(a.shape))

<class 'tuple'>


In [7]:
# create a 2-d array
b=np.array([[1,3,4],[5,6,7]]) # ',' means new coloumn starts
print(b)
print(b.shape)
print(b[1][2])

[[1 3 4]
 [5 6 7]]
(2, 3)
7


In [10]:
#create zero array amnd ones array
bb=np.zeros((3,4)) # it's accepts shape which is basically a tuple
print(bb)
c=np.ones((4,5))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
#create constant array 
const=np.full((4,3),6) # it accepts constant value and shape of that matrix
print(const)
print(type(const))

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]
<class 'numpy.ndarray'>


In [15]:
# create an Identity Matrix,which will be a square matrix
I=np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# create a random matrix ehich elements lie in b/w 0 and 1
RandomMatrix=np.random.random((2,4))
print(RandomMatrix)

[[0.75150655 0.43378447 0.25331693 0.87337603]
 [0.16290097 0.75047926 0.86023549 0.43570868]]


In [19]:
# return a sub array
sub_arr=RandomMatrix[:,1:2] # or can use 1:n but it'll give only till max coloumn
print(sub_arr)

[[0.43378447]
 [0.75047926]]


In [23]:
su_1=RandomMatrix[1:2,2:3] # here 1:n means excluding nth col
print(su_1)

[[0.86023549]]


In [24]:
# update any sub_array part of given array
RandomMatrix[1:3,1:3]=4
print(RandomMatrix)

[[0.75150655 0.43378447 0.25331693 0.87337603]
 [0.16290097 4.         4.         0.43570868]]


In [25]:
#data types

In [28]:
z=np.zeros((2,3))
print(z)
print(z.dtype) # dtype is an attribute not method


[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [29]:
z=np.zeros((2,3),dtype=np.int64)

In [30]:
print(z.dtype)

int64


In [35]:
# Mathematical Calculation on Matrix 
#1 element wise addition 
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)
print(x+y)
print(np.add(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [33]:
#2 element wise subtraction
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [34]:
#3 element wise multiplication
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [36]:
#4 element wise division
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [37]:
# 5
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [38]:
# dot product
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [39]:
# dot product of two vectors=> scalar
xx=np.array([1,2,3,4])
yy=np.array([1,2,3,4])
print(np.dot(xx,yy))

30


In [40]:
print(type(np.dot(xx,yy))) # scalar ,it's not an numpy.array

<class 'numpy.int32'>


In [48]:
# sum on array (np)
print(x)
print(sum(x))
print(np.sum(x))
print(np.sum(x,axis=0)) # give sum of coloumns in 1x(c) 
print(type(sum(x))) # NOTE=> sum of any array is not scalar
print(type(np.sum(x,axis=0)))
print(type(sum(xx))) # BUT sum of vector is scalar
print(np.sum(x,axis=1)) # give sum accross row in 1x(r)
print(type(np.sum(x,axis=1)))


[[1 2]
 [3 4]]
[4 6]
10
[4 6]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>
[3 7]
<class 'numpy.ndarray'>


In [49]:
# Stacking of array
print(xx)
print(yy)
yy=yy**2
print(yy)
aa=np.stack((xx,yy),axis=0) # along coloumn
ab=np.stack((xx,yy),axis=1) # along row
print(aa)
print(ab)

[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [52]:
# reshaping of Numpy array
test=np.array([[1,2,3,4],[5,6,7,8]])
test1=test.reshape((2,4)) # reshape is a method not an attribute
test2=test.reshape((-1,4)) # if we know omly about row or coloumn then just put known value and -1 instead of unknown value
test3=test.reshape((4,-1))

In [53]:
print(test)
print(test1)
print(test2)
print(test3)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [56]:
ex=np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

[2 1 4 3]
[4 3 1 2]
