In [4]:

a=np.array([[1,2,3,4],[5,6,7,8]])
mn=np.min(a)
mx=np.max(a)
mn_1=np.min(a,axis=0)
mn_2=np.min(a,axis=1)
print(mn)
print(mn_1)
print(mn_2)

1
[1 2 3 4]
[1 5]


In [2]:
import numpy as np

In [5]:
men=np.mean(a)
men_1=np.mean(a,axis=0)
men_2=np.mean(a,axis=1)
print(men)
print(men_1)
print(men_2)

4.5
[3. 4. 5. 6.]
[2.5 6.5]


In [6]:
print(np.median(a)) # median is median element in sorted array

4.5


In [16]:
# mean vs average
c=np.array([1,2,7,8,9])
print(np.mean(c))
#weights
wts=np.array([1,2,7,8,9])
avg=np.average(c,weights=wts)
print(avg)
wts_1=np.array([1,1,1,1,1])
print(np.average(c,weights=wts_1))

5.4
7.37037037037037
5.4


In [17]:
print(c-2) # it is possible

[-1  0  5  6  7]


In [19]:
# standard deviation
u=np.mean(c)
myStd=np.sqrt(np.mean((c-u)**2))
print(myStd)
 # using Inbuilt function
dev=np.std(c)
print(dev)

3.2619012860600183
3.2619012860600183


In [21]:
# variance
var_=dev**2
print(var_)
#inbuilt finction
var_1=np.var(c)
print(var_1)

10.64
10.64
