In [2]:
import numpy as np
import pandas as pd

In [3]:
x=np.random.randint(1,100,5)
print(x)
print(type(x))

[95 26 97 61 62]
<class 'numpy.ndarray'>


In [4]:
xx=list(x)
print(xx)
print(type(xx))

[95, 26, 97, 61, 62]
<class 'list'>


In [5]:
user_data={
    "marks A":list(np.random.randint(1,100,5)),
    "marks B":list(np.random.randint(1,100,5)),
    "marks C":list(np.random.randint(1,100,5))
    
}
print(type(user_data))

<class 'dict'>


In [6]:
# data frame
df=pd.DataFrame(user_data,dtype='float32')


In [7]:
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
   marks A  marks B  marks C
0      7.0     51.0     96.0
1     73.0     39.0     51.0
2     84.0     58.0     10.0
3     87.0     77.0     57.0
4      5.0     77.0     95.0


In [8]:
print(df.head())
print(df.head(3))

   marks A  marks B  marks C
0      7.0     51.0     96.0
1     73.0     39.0     51.0
2     84.0     58.0     10.0
3     87.0     77.0     57.0
4      5.0     77.0     95.0
   marks A  marks B  marks C
0      7.0     51.0     96.0
1     73.0     39.0     51.0
2     84.0     58.0     10.0


In [9]:
# df to csv file
# file name=marks.csv
df.to_csv("marks.csv")

In [10]:
my_data=pd.read_csv("marks.csv")
print(my_data)
print(type(my_data))

   Unnamed: 0  marks A  marks B  marks C
0           0      7.0     51.0     96.0
1           1     73.0     39.0     51.0
2           2     84.0     58.0     10.0
3           3     87.0     77.0     57.0
4           4      5.0     77.0     95.0
<class 'pandas.core.frame.DataFrame'>


In [11]:
# to drom a coloumn from my data file
my_data=my_data.drop(columns=['Unnamed: 0'])
print(my_data)
print(type(my_data))# still a data frame

   marks A  marks B  marks C
0      7.0     51.0     96.0
1     73.0     39.0     51.0
2     84.0     58.0     10.0
3     87.0     77.0     57.0
4      5.0     77.0     95.0
<class 'pandas.core.frame.DataFrame'>


## Panda Basics-2

In [20]:
 # describe a my_data
print(my_data.describe())

         marks A    marks B    marks C
count   5.000000   5.000000   5.000000
mean   58.000000  36.600000  52.600000
std    34.022052  19.969977  32.400617
min     9.000000  16.000000   7.000000
25%    50.000000  17.000000  36.000000
50%    52.000000  38.000000  60.000000
75%    81.000000  52.000000  68.000000
max    98.000000  60.000000  92.000000


In [21]:
my_data.tail(2)

marks A  marks B  marks C
3     98.0     38.0     36.0
4     50.0     52.0     68.0

In [12]:
# how to access particu;ar row or column
# row
print(my_data.iloc[2])
print(type(my_data.iloc[2]))# but this is not a data frame (it's a series but still array-like DS so we can convert it to Data Frames)

marks A    84.0
marks B    58.0
marks C    10.0
Name: 2, dtype: float64
<class 'pandas.core.series.Series'>


- we can convert this data into list and dict also but dict is preferrable

In [27]:
lp=my_data.iloc[2]
lp_l=list(lp)
lp_dict=dict(lp)

In [28]:
print(lp_l)
print(lp_dict)

[9.0, 17.0, 92.0]
{'marks A': 9.0, 'marks B': 17.0, 'marks C': 92.0}


In [29]:
print(type(lp_l))
print(type(lp_dict))

<class 'list'>
<class 'dict'>


In [33]:
# Row & column
print(my_data.iloc[3,1])
print(type(my_data.iloc[3,1]))

38.0
<class 'numpy.float64'>


In [37]:
# how to find column index in my_data
idx=my_data.columns.get_loc('marks A')
print(idx)

0


In [38]:
# same for df 
idx=my_data.columns.get_loc('marks A')
print(idx)

0


In [39]:
print(my_data.iloc[3][1])

38.0


In [40]:
idx=[my_data.columns.get_loc('marks A'),my_data.columns.get_loc('marks C')]
print(idx)
print(my_data.iloc[:3,idx])

[0, 2]
   marks A  marks C
0     52.0      7.0
1     81.0     60.0
2      9.0     92.0


In [43]:
dct=my_data.iloc[:,[1,2]]
print(my_data.iloc[:,[1,2]])

   marks B  marks C
0     60.0      7.0
1     16.0     60.0
2     17.0     92.0
3     38.0     36.0
4     52.0     68.0


In [50]:
# How to traverse
# so to traverse convert data_fram or my_data in traversable Data Syricture like Dict or List but if Data has rows and columns then
# it is preferrable using nested dict ;like we donr below ->dictionary after dictionory
# Or we can use np.arrya as we can convert it to np.array using < my_data.values >
dct=dict(dct)
#print(dct)
print(dct['marks B'])
lst=list(dct['marks B'])
lst_dict=dict(dct['marks B'])
print(type(dct['marks B']))
print(lst)
print(type(lst))
print(lst_dict)
print(type(lst_dict))

0    60.0
1    16.0
2    17.0
3    38.0
4    52.0
Name: marks B, dtype: float64
<class 'pandas.core.series.Series'>
[60.0, 16.0, 17.0, 38.0, 52.0]
<class 'list'>
{0: 60.0, 1: 16.0, 2: 17.0, 3: 38.0, 4: 52.0}
<class 'dict'>


In [ ]:
## Sorting on data_frame

In [51]:
my_data

marks A  marks B  marks C
0     52.0     60.0      7.0
1     81.0     16.0     60.0
2      9.0     17.0     92.0
3     98.0     38.0     36.0
4     50.0     52.0     68.0

In [53]:
sort_1=my_data.sort_values(by=['marks A'],ascending=True)
print(sort_1)

   marks A  marks B  marks C
2      9.0     17.0     92.0
4     50.0     52.0     68.0
0     52.0     60.0      7.0
1     81.0     16.0     60.0
3     98.0     38.0     36.0


In [54]:
sort_2=my_data.sort_values(by=['marks B'],ascending=False)
print(sort_2)
print(my_data)

   marks A  marks B  marks C
0     52.0     60.0      7.0
4     50.0     52.0     68.0
3     98.0     38.0     36.0
2      9.0     17.0     92.0
1     81.0     16.0     60.0
   marks A  marks B  marks C
0     52.0     60.0      7.0
1     81.0     16.0     60.0
2      9.0     17.0     92.0
3     98.0     38.0     36.0
4     50.0     52.0     68.0


In [56]:
sort_3=my_data.sort_values(by=['marks C','marks A'],ascending=False) # priority goes to c 
print(sort_3)

   marks A  marks B  marks C
2      9.0     17.0     92.0
4     50.0     52.0     68.0
1     81.0     16.0     60.0
3     98.0     38.0     36.0
0     52.0     60.0      7.0


In [57]:
# convert into np.array 
data_array=my_data.values
print(type(data_array))
print(data_array)

<class 'numpy.ndarray'>
[[52. 60.  7.]
 [81. 16. 60.]
 [ 9. 17. 92.]
 [98. 38. 36.]
 [50. 52. 68.]]


In [58]:
## Numpy array to Data Frame **imp
new_df=pd.DataFrame(data_array,dtype='int32',columns=["physics","chemistry","math"])
print(new_df)

   physics  chemistry  math
0       52         60     7
1       81         16    60
2        9         17    92
3       98         38    36
4       50         52    68


In [62]:
## new_df to csv file 
new_df.to_csv("pcm.csv",index=False) # to avoid unnamed extra indexing column otherwise we'll have to remove usinf drop method


In [64]:
pcm=pd.read_csv('pcm.csv')
print(pcm)

   physics  chemistry  math
0       52         60     7
1       81         16    60
2        9         17    92
3       98         38    36
4       50         52    68


In [65]:
# so again to find np.array
np_array=pcm.values
print(np_array)
print(type(np_array))

[[52 60  7]
 [81 16 60]
 [ 9 17 92]
 [98 38 36]
 [50 52 68]]
<class 'numpy.ndarray'>


### NOTE: all operation on data frames like getting column,getting row, sorting col. droping doesn't change it's data type (still Data frame
