- broadcasting

In [2]:
import numpy as np

In [3]:
a=np.array([[1,2],[3,4]]) # 2x2 array
v=np.array([1,2]) # vector


In [4]:
#1 adding a scalar to vector 
v1=v+5
print(v1)

[6 7]


In [5]:
#2 adding a vectro and matrix
m=a+v # vector will add ot each coloumn of array a-> 1st element of vector to 1st whole column of matrix and 2nd to 2nd 
# and so on
print(a)
print(v) # shape->(2,)-> means a vector having 2 elements
print(v.shape)
print(m)

[[1 2]
 [3 4]]
[1 2]
(2,)
[[2 4]
 [4 6]]


### If we define a vector or matrix of zeros and onesusing np array and sape -> 1.for vector: v=np.array((shape))-> shape=(no_of _elm,)
### but for matrix m=np.array((shape))-> shape=(r,c)
#### eg. v=np.zeros((3,)) m=np.zeros((3,4))

In [7]:
v=np.zeros((3,))
mat=np.zeros((3,5))
print(v)
print(mat)
print(type(v),type(mat))
print(v.shape,mat.shape)

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(3,) (3, 5)


In [8]:
#3 multiply scalar to matrix
# it'll multiply each element of matrix
a2=a*3
print(a2)

[[ 3  6]
 [ 9 12]]


In [10]:
#4 multiplying a matrix and vector 
#it will multiply to each coloumn in element-wise mltiplication->1st element to first col and 2nd element(of vector )
# to 2nd column of matrix.....etc
a3=a*v
print(a3)
# NOTE_> to multiply a matrix and vector vector's element and matrix 's columns must be same'

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [11]:
a=np.array([[1,2,3],[4,5,6]])
va=np.array([4,4,4])
print(a*va)
print(va*a)

[[ 4  8 12]
 [16 20 24]]
[[ 4  8 12]
 [16 20 24]]


In [12]:
#5 adding a scalar to matrix
print(a)
a_m=a+5
print(a_m)

[[1 2 3]
 [4 5 6]]
[[ 6  7  8]
 [ 9 10 11]]
