In [1]:
import numpy as np


In [3]:
a=np.array([3,4])
print(a)
#l1 norm
lp1=np.linalg.norm(a,ord=1)
lp2=np.linalg.norm(a,ord=2)# also default norm
print(lp1)
print(lp2)

[3 4]
7.0
5.0


In [5]:
# l infinity norm
# in this case we get largest absolute value of vector
lpinf=np.linalg.norm(a,ord=np.inf)
print(lpinf)

4.0


## Determinants

In [6]:
d=np.array([[1,2],[3,4]])
print(d)
dt=np.linalg.det(d)
print(dt)

[[1 2]
 [3 4]]
-2.0000000000000004


## Inverse

In [8]:
d_inv=np.linalg.inv(d)
print(d_inv)
print(np.dot(d,d_inv)) # return s an Identity matrix

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Pseudo Inverse

In [9]:
# if given matrix is non-invertible the we use pseudo inveres
# but it'll also give correct result for invertible-matrix also
A=np.array([[3,4],
            [3,4]]) # det of this A array is zero-> so it's non-invertible matrix
A_inv=np.linalg.pinv(A)
print(A_inv)

[[0.06 0.06]
 [0.08 0.08]]


In [10]:
print(np.dot(A,A_inv))

[[0.5 0.5]
 [0.5 0.5]]


In [11]:
print(np.linalg.pinv(d))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
## NOTE:> pinv() is used in sloving equation ..whether arrays are invertible or not

## Solve a System of Equations

In [14]:
#2*x1 + 3*x2=8
# 3*x1 + x2=5
# it's a linear equation in the form of AX=B
a=np.array([[2,3],[3,1]],dtype='int8')
b=np.array([8,5],dtype='int8')
x=np.linalg.solve(a,b)
print(x)
print(type(x))

[1. 2.]
<class 'numpy.ndarray'>
